name: square-number
description: takes in an input number and returns its square
inputs:
  num:
    description: the number to square
    required: true
  string-arg:
    description: test-string
    required: false
    default: default-string
  bool-arg:
    description: test-bool
    required: false
    default: true
outputs:
  num-squared:
    description: the input squared
    value: ${{ steps.get-square.outputs.num-squared }}

runs:
  using: "composite"
  steps:
    - id: get-square
      shell: bash
      env:
        INPUT_NUM: ${{ inputs.num }}
        INPUT_NUM_JSON: ${{ toJSON(inputs.num) }}
      run: |-
        PYTHONPATH="$GITHUB_ACTION_PATH/src" python -m square_number
        env
